### ISSUE TITLE
Decide whether to use one-space indent in some cases

### ISSUE THREAD

**Issue by cespare** [cespare/goclj#27]
The Clojure Style Guide [recommends](https://github.com/bbatsov/clojure-style-guide#one-space-indent) using a one-space indent for list forms where there's only one element on the first line **and** the first element isn't one of the "forms that have body parameters" (def*, let, loop, when, etc. -- in cljfmt terminology, one of the `indentSpecial`s.)

In #9, we applied a blanket two-space indent for list forms with only one element before the newline, regardless of what the element is. Should we go with the Clojure Style Guide's recommendation instead?

**Comment by cespare** [comment]
A concrete example:

``` clojure
; here's what cljfmt does today
(filter
  even?
  (range 1 10))

; here's what the style guide recommends
(filter
 even?
 (range 1 10))
```

At Liftoff, it seems like the vim users use the former and the emacs users use the latter.

**Comment by dmac** [comment]
I prefer the former; we diverge from the Clojure Style Guide in other ways, so I don't think we need to stick to it strictly.

**Comment by cespare** [comment]
We're happy with the way we're doing it.
