### ISSUE TITLE
Indent open questions

### ISSUE THREAD

**Issue by cespare** [cespare/goclj#36]
Here are some formattings we could consider preserving.

``` clojure
; map indent
{:foo
   2}

; assoc indent
(assoc foo
       :blah
         3)
```

**Comment by dmac** [comment]
These would be consistent with

```clojure
(case foo
  :bar
    2)
```

but I also feel like they come up much less frequently than `case`. I don't feel strongly, so prefer path of least resistance.

**Comment by cespare** [comment]
One reason not to do the `assoc` one is that it's very often used in threading contexts where the body argument will be missing. So if we indented all the odd-numbered arguments (after 1), it would look like

``` clojure
(assoc foo
       :bar
         3
       :baz
         4)

(-> foo
    (assoc :bar
           3
             :baz
           4))
```

**Comment by cespare** [comment]
Maps are now indented. That seems like a nice change.

I'm leaning towards no for `assoc`. It's trivial to do now (just set the indent style for `"assoc"` to `IndentCond1`) but I think it's best avoided because of how often assoc is used with an implicit first arg in threaded expressions.

**Comment by cespare** [comment]
Given #40 (adding threading-awareness), indentation for assoc should be doable as well.

**Comment by cespare** [comment]
Assoc is now indented as well. Closing this out.
