### ISSUE TITLE
Enforce newline style in if-expressions

### ISSUE THREAD

**Issue by dmac** [cespare/goclj#52]
Currently cljfmt allows if-expressions that look like this:

```clojure
(if foo? a
  b)
```

This proposal would have it move the true-branch to its own line when the false-branch is not on the same line as the "if":

```clojure
(if foo?
  a
  b)
```

One-line if-expressions like `(if foo? a b)` would **not** be reformatted.

**Comment by cespare** [comment]
I think this makes sense. It requires adding a new indent style, I think. Right now `if` uses `IndentListBody`, the same style as `def`, `defn`, and a host of other functions. I think we should add:

```
	// IndentIf is for list forms like if. Subsequent lines are indented by
	// two spaces. If both 'then' and 'else' are provided, then the whole
	// form must be a single line or else the 'then' and 'else' must both be
	// on new lines.
	//   (if x y z)
	//   (if-not a
	//     b
	//     c)
	IndentIf
```

and then use it for `if`, `if-not`, `if-let`, and `if-some`.

**Comment by cespare** [comment]
I implemented this a different way by adding a new transform `fix-if-newline-consistency`. See #84.
