### ISSUE TITLE
remove-unused-requires will remove `[a.b :as b]` if `b` is unused

### ISSUE THREAD

**Issue by adeodatus** [cespare/goclj#57]
Given a require `[a.b :as b]` it is legal to refer to fields within that namespace as `b/field` or `a.b/field`. If we only refer to fields with the latter form `a.b/field` then `remove-unused-requires` will remove the require erroneously.

In this case it's probably desirable to remove the `:as b` portion, but that is not required to fix the bug.

**Comment by cespare** [comment]
I think there's a missing piece to this report. It's not generally required to keep this `require` in the situation you've described; you can refer to a fully-qualified namespace without `require`ing it at all:

```
user=> (clojure.string/blank? "")
true
user=> (require '[clojure.string :as s])
nil
user=> (s/blank? "")
true
```

**Comment by dmac** [comment]
@cespare I think that's only valid when some other namespace has already required `clojure.string`. 

```
> pwd
/Users/dmac/work/src/liftoff/ml_lib
> lein repl
user=> (shared-lib.core/sget {:a 1} :a)

ClassNotFoundException shared-lib.core  java.net.URLClassLoader.findClass (URLClassLoader.java:381)
user=> (require '[shared-lib.core])
nil
user=> (shared-lib.core/sget {:a 1} :a)
1
```

**Comment by cespare** [comment]
Ah, that makes sense. I guess we have to conservatively leave these in, then.
