### ISSUE TITLE
Exit with non zero code when list is not empty

### ISSUE THREAD

**Issue by tzzh** [cespare/goclj#70]
When `cljfmt -l` is not empty it would be nice to exit with a non zero exit code.
It's then easier to integrate it with build pipelines for example.

**Comment by cespare** [comment]
I prefer to keep the gofmt behavior here. Non-zero exit codes are only for the case that there is some error reading/parsing the input files. To incorporate into a build pipeline, a simple script should suffice. For instance, you could do

    test -z $(cljfmt -l *.clj) 

or

    cljfmt -l *.clj | tee >(test -z)

if you want to print the list as well (the last one assumes a shell, such as Bash, with process substitution).
