### ISSUE TITLE
Handle the :let modifier for doseq and for

### ISSUE THREAD

**Issue by tao-liu-liftoff** [cespare/goclj#73]
When using the `:let` modifier for macros such as `for` and `doseq`, cljfmt does not format indentation correctly.

Example:

```clojure
(for [x (range 10)
      :let [y
            (+ x 1)
            z
            (+ x 2)]]
  (println x y z))

(doseq [x (range 10)
        :let [y
              (+ x 1)
              z
              (+ x 2)]]
  (println x y z))
```

Expected:

```clojure
(for [x (range 10)
      :let [y
              (+ x 1)
            z
              (+ x 2)]]
  (println x y z))
```

**Comment by cespare** [comment]
This is similar to #69.

**Comment by mrkam2** [comment]
Had the same issue. How can I help with the fix? I added a branch with the failing testcase: https://github.com/cespare/goclj/compare/master...liftoffio:alexk.doseq-let?expand=1

**Comment by cespare** [comment]
> How can I help with the fix?

You can write it and send a PR.

**Comment by mrkam2** [comment]
Makes sense. I'm not familiar with this project yet. Could you please share your initial thoughts on how this feature could be implemented assuming the shape of the existing codebase?

**Comment by mrkam2** [comment]
Added a PR https://github.com/cespare/goclj/pull/78. Can't assign you as a reviewer for some reason. @cespare
