### ISSUE TITLE
Doseq and for should use let-style indentation

### ISSUE THREAD

**Issue by cespare** [cespare/goclj#76]
All the indicated lines should be indented:

```
(for [x
      [1 2 3] ; <--
      y
      [4 5 6]] ; <--
  [x y])

(doseq [x
        [1 2 3] ; <--
        y
        [4 5 6]] ; <--
  (println x y))
```

When fixing this, we should do a quick skim to see if there are other `IndentListBody`s that should be `IndentLet`s.

**Comment by mrkam2** [comment]
Added a PR https://github.com/cespare/goclj/pull/78
